---
title: "Muestreo Aleatorio Estratificado"
author: "Christian Javier Salas Marquez"
date: "Enero de 2022"
output:
  pdf_document: default
  html_notebook: default
  number_sections: yes
  df_print: paged
  toc: yes
  toc_depth: 3
  toc_float: yes
  html_document:
    df_print: paged
---


***
## LaTex
***

Se utiliza la fórmula para determinar el tamaño de la MAE con afijación proporcional considerando al parámetro de la Media Poblacional del Impuesto a la Renta Causado.

$$
n_0= \dfrac{\lambda_{\alpha/2}^2 \sum_{h=1}^{L} \left[\dfrac{N_h}{N}\right] S_h^{2}}{e^2}
$$

$$
n = \dfrac{n_0}{1+\dfrac{n_0}{N}}
$$

Donde:

\begin{itemize}
\item $n$ = Tamaño muestral
\item $\lambda_{\alpha/2}$ = Coeficiente de confianza
\item $L$ = Número de estratos
\item $N$ = Tamaño poblacional
\item $N_h$ = Tamaño del estrato h
\item $S_h^2$ = Varianza del estrato h
\item $e$ = Error absoluto
\end{itemize}

Reemplazando

\begin{itemize}
\item $\lambda_{\alpha/2}$ = 1.96
\item $L$ = 4
\item $N$ = 10642
\item $N_1$ = 2153
\item $N_2$ = 4052
\item $N_3$ = 3082
\item $N_4$ = 1355
\item $S_1^2$ = 5.911175e+12
\item $S_2^2$ = 4365501789
\item $S_3^2$ = 413208878
\item $S_4^2$ = 1877296812
\item $e$ = 100000
\end{itemize}

Calculamos el peso de cada estrato

$$
W_h = \dfrac{N_h}{N}
$$

De donde obtenemos

\begin{itemize}
\item $W_1$ = 0.2023116
\item $W_2$ = 0.3807555
\item $W_3$ = 0.2896072
\item $W_4$ = 0.1273257
\end{itemize}


$$
n_0= \dfrac{1.96^2 \left[ \left[\dfrac{N_1}{N} \times S_1^{2}\right] + \left[\dfrac{N_2}{N} \times S_2^{2}\right] +\left[\dfrac{N_3}{N} \times S_3^{2}\right] +\left[\dfrac{N_4}{N} \times S_4^{2}\right]\right]}{e^2}
$$

$$
n_0= \dfrac{1.96^2 \left[ \left[\dfrac{2153}{10642} \times (5.9\times10^{12})\right] + \left[\dfrac{4052}{10642} \times 4365501789\right] +\left[\dfrac{3082}{10642} \times413208878\right] +\left[\dfrac{1355}{10642} \times 1877296812\right]\right]}{100000^2}
$$

$$
n_0 = 460.193
$$

Luego

$$
n = \dfrac{460.193}{1+\dfrac{460.193}{10642}}
$$

$$
n = 441.1177 \approx 441
$$

Posteriormente, calculamos el tamaño de muestra de cada estrato por medio de la afijación proporcional

$$
n_h = W_h \times n
$$

De donde obtenemos

\begin{itemize}
\item $n_1 = W_1 \times n = 0.2023116 \times 441.1177 = 89.24323 \approx 89 $
\item $n_2 = W_2 \times n =  0.3807555 \times 441.1177 = 167.958 \approx 168 $
\item $n_3 = W_3 \times n = 0.2896072 \times 441.1177 =  127.7509 \approx 128 $
\item $n_4 = W_4 \times n =  0.1273257 \times 441.1177 = 56.16562 \approx 56 $
\end{itemize}

\begin{itemize}
\item $n_1 =  89 $
\item $n_2 =  168 $
\item $n_3 =  128 $
\item $n_4 = 56 $
\end{itemize}


Finalmente, calculamos la estimación de la media poblacional con el siguiente estimador


$$
\bar{x} = \sum_{h=1}^L \left[ \dfrac{N_h}{N} \right] \bar{x}_h
$$

donde

\begin{itemize}
\item $\bar{x}_h$ = Media muestral del estrato $h$
\end{itemize}


Se calcula la media de cada estrato de las empresas obtenidas de la muestra i.e. la media muestral de cada estrato


\begin{itemize}
\item $\bar{x}_1 = 585691.9$ 
\item $\bar{x}_2 = 39858.83$ 
\item $\bar{x}_3 = 12558.06$ 
\item $\bar{x}_4 = 3404.42$ 
\end{itemize}


Finalmente, reemplazando los valores respectivos en la fórmula


$$
\bar{x} = \left[ \left[ \dfrac{N_1}{N}  \bar{x}_1 \right] + \left[ \dfrac{N_2}{N}  \bar{x}_2 \right] + \left[ \dfrac{N_3}{N}  \bar{x}_3 \right] + \left[ \dfrac{N_4}{N}  \bar{x}_4 \right] \right]
$$


$$
\bar{x} = \left[ \left[ \dfrac{2153}{10642} \times  585691.9 \right] + \left[ \dfrac{4052}{10642} \times  39858.83 \right] + \left[ \dfrac{3082}{10642} \times  12558.06 \right] + \left[ \dfrac{1355}{10642} \times  3404.42 \right] \right]
$$


$$
\bar{x} = 137739.1
$$

Podemos ver que la estimación de la media poblacional del impuesto a la renta causado por las empresas es de 137739.1 mientras que la media poblacional real de este indicador está dada por 137779.8







